routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('videoblob', VideoblobController::class);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Videoblob.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Videoblob extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/VideoblobController.php
<?php

namespace App\Http\Controllers;

use App\videoblob;
use FFMpeg;
use Illuminate\Http\Request;

class VideoblobController extends Controller
{

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create_video');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' =>'required',
            'publish_date' =>'required',
            'video'  => 'required|mimes:mp4',
            'poster' =>'required|image|mimes:jpg,png,gif',
           ]);
            $poster = $request->file('poster');
            $new_poster = rand() . '.' . $poster->getClientOriginalExtension();
            $poster->move(public_path('images'), $new_poster);
            $video = $request->file('video');
            $new_video = rand() . '.' . $video->getClientOriginalExtension();
            $video->move(public_path('videos/original'), $new_video);
            copy(public_path('videos/original').'/'.$new_video,public_path('videos/preview').'/'.$new_video);
            $videoblob = new videoblob;

            $videoblob->title = $request->title;
            $videoblob->publish_date = date('Y-m-d',strtotime($request->publish_date));
            $videoblob->is_active = 1;
            $videoblob->video = $new_video;
            $videoblob->poster = $new_poster;
            $videoblob->save();
            try{
                $ffmpeg = FFMpeg\FFMpeg::create();
                $short_video=public_path('videos/preview').'/'.$new_video;
                $attributes=_get_video_attributes($short_video,$ffmpeg);
                $preview_time=$attributes['secs']*02;
                $video = $ffmpeg->open($short_video);
                $clip = $video->clip(FFMpeg\Coordinate\TimeCode::fromSeconds($preview_time), FFMpeg\Coordinate\TimeCode::fromSeconds($preview_time));
            $clip->save(new FFMpeg\Format\Video\X264(), $short_video);
            }catch(Exception $e){
                return redirect()->route('videoblob.create');
            }
            finally {
                return redirect()->route('videoblob.create');
            }

        // echo 3;exit;
       return redirect()->route('videoblob.create');
    }

    public function fetchvideo(){
        $videoblob = Videoblob::where('publish_date', '<=', date('Y-m-d'))->select('id','title','video','poster')->get();
        return response()->json(['data' => $videoblob->toArray()], 200);
    }

}

resources/views/create_video.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>videoblob</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">

            <div class="content">
            <form method="POST" action="{{ route('videoblob.store') }}" aria-label="{{ __('video') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-sm-4 col-form-label text-md-right">{{ __('Title') }}</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}"  autofocus>

                                @if ($errors->has('title'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="publish_date" class="col-sm-4 col-form-label text-md-right">{{ __('Publish Date') }}</label>

                            <div class="col-md-6">
                                <input id="publish_date" type="date" class="form-control{{ $errors->has('publish_date') ? ' is-invalid' : '' }}" name="publish_date" value="{{ old('publish_date') }}" >

                                @if ($errors->has('publish_date'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('publish_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="video" class="col-sm-4 col-form-label text-md-right">{{ __('Video') }}</label>

                            <div class="col-md-6">
                                <input id="video" type="file" class="form-control{{ $errors->has('video') ? ' is-invalid' : '' }}" name="video" value="{{ old('video') }}" >

                                @if ($errors->has('video'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('video') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="poster" class="col-sm-4 col-form-label text-md-right">{{ __('poster') }}</label>

                            <div class="col-md-6">
                                <input id="poster" type="file" class="form-control{{ $errors->has('poster') ? ' is-invalid' : '' }}" name="poster" value="{{ old('poster') }}" >

                                @if ($errors->has('poster'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('poster') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Upload') }}
                                </button>
                            </div>
                        </div>
                    </form>
            </div>
        </div>
    </body>
</html>

resources/views/index.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>video</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="team-grid">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Video Gallery </h2>
                <p class="text-center"> </p>
            </div>
            <div id="view_grid">
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</body>
<!-- <script src="https://code.jquery.com/jquery-2.2.4.js"></script> -->
<script src="js/custom.js"></script>
<script>
    // alert(window.location.href);
    var uri=window.location.href;
window.onload=callvideoresource();
</script>
</html>